
services:

  xiidea.easy_audit.logger_factory:
          class: Xiidea\EasyAuditBundle\Logger\LoggerFactory
          public: false
          arguments : [ '%xiidea.easy_audit.logger_channel%' ]
          calls:
              - [ setDebug,[ '%kernel.debug%' ] ]

  xiidea.easy_audit.event_resolver_factory:
          class: Xiidea\EasyAuditBundle\Resolver\EventResolverFactory
          public: false
          arguments : [ '%xiidea.easy_audit.custom_resolvers%', '%xiidea.easy_audit.user_property%', '%xiidea.easy_audit.audit_log_class%' ]
          calls:
            - [ setAuthChecker,[ '@security.authorization_checker' ] ]
            - [ setRequestStack,[ '@request_stack' ] ]
            - [ setTokenStorage,[ '@security.token_storage' ] ]
            - [ setDebug,[ '%kernel.debug%' ] ]

  xiidea.easy_audit.event_listener:
          class: Xiidea\EasyAuditBundle\Listener\LogEventsListener
          arguments: ['@xiidea.easy_audit.logger_factory', '@xiidea.easy_audit.event_resolver_factory']

  xiidea.easy_audit.mono_logger.service:
          class: Xiidea\EasyAuditBundle\Logger\MonologLogger
          arguments: ['@logger']
          public: false,
          tags:
             - { name: easy_audit.logger }
             - { name: monolog.logger, channel: easy_audit }